name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [
          ubuntu,
          macos
        ]
        include:
          - name: ubuntu
            os: ubuntu-latest
          - name: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v2

      - name: Configure, build and test with CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON  -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
